//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestfulServiceForAndroidProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public Cours()
        {
            this.Student_Course = new HashSet<Student_Course>();
            this.Teacher_Course = new HashSet<Teacher_Course>();
        }
    
        public int CID { get; set; }
        public string CName { get; set; }
    
        public virtual ICollection<Student_Course> Student_Course { get; set; }
        public virtual ICollection<Teacher_Course> Teacher_Course { get; set; }
    }
}
