//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestfulServiceForAndroidProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.Project_Group = new HashSet<Project_Group>();
            this.Student_Group = new HashSet<Student_Group>();
        }
    
        public int GID { get; set; }
        public string GName { get; set; }
    
        public virtual ICollection<Project_Group> Project_Group { get; set; }
        public virtual ICollection<Student_Group> Student_Group { get; set; }
    }
}
