//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestfulServiceForAndroidProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NID { get; set; }
        public string NMessage { get; set; }
        public string NSenderID { get; set; }
        public string NReceiverID { get; set; }
        public string NReceiverType { get; set; }
    }
}
