//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestfulServiceForAndroidProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Project_Group = new HashSet<Project_Group>();
            this.Teacher_Project = new HashSet<Teacher_Project>();
        }
    
        public int PID { get; set; }
        public string PTitle { get; set; }
        public string PDescription { get; set; }
    
        public virtual ICollection<Project_Group> Project_Group { get; set; }
        public virtual ICollection<Teacher_Project> Teacher_Project { get; set; }
    }
}
