//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestfulServiceForAndroidProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_Group
    {
        public int PG_ID { get; set; }
        public int PID { get; set; }
        public int GID { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Project Project { get; set; }
    }
}
