//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestfulServiceForAndroidProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MC_ProjectAssignerEntities : DbContext
    {
        public MC_ProjectAssignerEntities()
            : base("name=MC_ProjectAssignerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cours> Courses { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Project_Group> Project_Group { get; set; }
        public virtual DbSet<Student_Course> Student_Course { get; set; }
        public virtual DbSet<Student_Group> Student_Group { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Teacher_Course> Teacher_Course { get; set; }
        public virtual DbSet<Teacher_Project> Teacher_Project { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
    }
}
