//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestfulServiceForAndroidProject.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Student_Course = new HashSet<Student_Course>();
            this.Student_Group = new HashSet<Student_Group>();
        }
    
        public string SEmailID { get; set; }
        public string Password { get; set; }

        [JsonIgnore]
        public virtual ICollection<Student_Course> Student_Course { get; set; }
        [JsonIgnore]
        public virtual ICollection<Student_Group> Student_Group { get; set; }
    }
}
