//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestfulServiceForAndroidProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public Teacher()
        {
            this.Teacher_Course = new HashSet<Teacher_Course>();
            this.Teacher_Project = new HashSet<Teacher_Project>();
        }
    
        public string TEmailID { get; set; }
        public string TPassword { get; set; }
    
        public virtual ICollection<Teacher_Course> Teacher_Course { get; set; }
        public virtual ICollection<Teacher_Project> Teacher_Project { get; set; }
    }
}
