//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestfulServiceForAndroidProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher_Course
    {
        public int TC_ID { get; set; }
        public string TID { get; set; }
        public int CID { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
