//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestfulServiceForAndroidProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher_Project
    {
        public int TP_ID { get; set; }
        public string TID { get; set; }
        public int PID { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
